#!/usr/bin/env python3
"""Generate the Core 0.1 E1 initial-family coverage report."""

from __future__ import annotations

import argparse
import sys
from pathlib import Path

SCRIPT_DIR = Path(__file__).resolve().parent
if str(SCRIPT_DIR) not in sys.path:
    sys.path.insert(0, str(SCRIPT_DIR))

from audit_core_e1_coverage import (
    COVERAGE_PATH,
    INVENTORY_PATH,
    README_PATH,
    load_json,
    validate,
)

OUTPUT_PATH = Path("docs/dependency-map/generated/CORE_0.1_E1_COVERAGE.md")
BT = chr(96)


def render(root: Path) -> str:
    coverage = load_json(root / COVERAGE_PATH)
    inventory = load_json(root / INVENTORY_PATH)
    readme_text = (root / README_PATH).read_text(encoding="utf-8")
    errors = validate(coverage, inventory, readme_text, root)
    if errors:
        raise ValueError(
            "E1 coverage validation failed before generation:\n"
            + "\n".join(f"- {error}" for error in errors)
        )

    node_labels = {node["id"]: node["label"] for node in inventory["nodes"]}
    targets = coverage["targets"]
    represented = sum(1 for target in targets if target["status"] == "REPRESENTED")
    open_gaps = sum(1 for target in targets if target["status"] == "OPEN_GAP")

    lines: list[str] = []
    lines.append("# Core 0.1 E1 Initial-Family Coverage")
    lines.append("")
    lines.append(
        "> Generated from "
        + BT
        + "docs/dependency-map/CORE_0.1_E1_COVERAGE.json"
        + BT
        + ". Do not edit this file independently."
    )
    lines.append("")
    lines.append("**Status:** provisional contributor evidence; not E1 PASS")
    lines.append("")
    lines.append(coverage["authority_note"])
    lines.append("")
    lines.append("## Result")
    lines.append("")
    lines.append(f"- README initial concept families: {len(targets)}")
    lines.append(f"- Represented: {represented}")
    lines.append(f"- Open gaps: {open_gaps}")
    lines.append("")
    lines.append(
        "This result measures the repository's stated starting inventory only. "
        "The README explicitly describes that list as a starting inventory, so "
        "complete representation here is not proof that E1 is complete."
    )
    lines.append("")
    lines.append("## Coverage map")
    lines.append("")
    lines.append("| Initial concept family | Status | Inventory nodes | Rationale |")
    lines.append("|---|---|---|---|")
    for target in targets:
        labels = ", ".join(
            BT + node_labels[node_id] + BT
            for node_id in target["node_ids"]
        )
        lines.append(
            f"| {target['name']} | {target['status']} | {labels} | "
            f"{target['rationale']} |"
        )
    lines.append("")
    lines.append("## Limits")
    lines.append("")
    for item in coverage["limits"]:
        lines.append(f"- {item}")
    lines.append("")
    lines.append("## Reproduction")
    lines.append("")
    lines.append(BT * 3 + "bash")
    lines.append("python scripts/audit_core_e1_coverage.py")
    lines.append("python scripts/audit_core_e1_coverage.py --self-test")
    lines.append("python scripts/generate_core_e1_coverage.py --check")
    lines.append(BT * 3)
    lines.append("")
    return "\n".join(lines)


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument(
        "--root",
        type=Path,
        default=Path(__file__).resolve().parents[1],
        help="Repository root.",
    )
    parser.add_argument(
        "--check",
        action="store_true",
        help="Fail when the committed generated report is stale.",
    )
    parser.add_argument(
        "--stdout",
        action="store_true",
        help="Print the generated report without writing it.",
    )
    args = parser.parse_args()

    root = args.root.resolve()
    expected = render(root)
    output = root / OUTPUT_PATH

    if args.stdout:
        print(expected, end="")
        return 0

    if args.check:
        if not output.is_file():
            print(f"generated report is missing: {OUTPUT_PATH.as_posix()}")
            return 1
        actual = output.read_text(encoding="utf-8")
        if actual != expected:
            print(
                "generated E1 coverage report is stale; run "
                "python scripts/generate_core_e1_coverage.py"
            )
            return 1
        print("e1_generated_report_current=1")
        return 0

    output.parent.mkdir(parents=True, exist_ok=True)
    output.write_text(expected, encoding="utf-8")
    print(f"wrote {OUTPUT_PATH.as_posix()}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
