#!/usr/bin/env python3
"""Generate the Core 0.1 E3 teaching-hypothesis review document."""

from __future__ import annotations

import argparse
import sys
from collections import defaultdict
from pathlib import Path

SCRIPT_DIR = Path(__file__).resolve().parent
if str(SCRIPT_DIR) not in sys.path:
    sys.path.insert(0, str(SCRIPT_DIR))

from audit_core_dependency_inventory import load_inventory
from audit_core_e3_teaching_hypothesis import (
    HYPOTHESIS_PATH,
    load_hypothesis,
    validate,
)

OUTPUT_PATH = Path("docs/dependency-map/generated/CORE_0.1_E3_TEACHING_HYPOTHESIS.md")
BT = chr(96)


def render(root: Path) -> str:
    inventory = load_inventory(root)
    hypothesis = load_hypothesis(root)
    errors = validate(hypothesis, inventory, root)
    if errors:
        raise ValueError(
            "E3 hypothesis validation failed before generation:\n"
            + "\n".join(f"- {error}" for error in errors)
        )

    nodes = {node["id"]: node for node in inventory["nodes"]}
    stage_by_node: dict[str, int] = {}
    for stage in hypothesis["stages"]:
        for node_id in stage["node_ids"]:
            stage_by_node[node_id] = stage["stage"]

    incoming: dict[str, list[dict[str, object]]] = defaultdict(list)
    for edge in inventory["edges"]:
        if edge["order_constraint"] is True:
            incoming[edge["to"]].append(edge)

    lines: list[str] = []
    lines.append("# Core 0.1 E3 Dependency-Derived Teaching Hypothesis")
    lines.append("")
    lines.append(
        "> Generated from "
        + BT
        + HYPOTHESIS_PATH.as_posix()
        + BT
        + ". Do not edit this file independently."
    )
    lines.append("")
    lines.append("**Status:** provisional teaching hypothesis; not E3 PASS")
    lines.append("")
    lines.append(hypothesis["authority_note"])
    lines.append("")
    lines.append("## Interpretation")
    lines.append("")
    lines.append(
        "The ordered stages below are the exact topological layers produced by "
        "the current HARD and STRONG dependency edges."
    )
    lines.append(
        "Nodes inside one stage are intentionally unordered. Their display order "
        "is for readability only and is not a mathematical or curricular claim."
    )
    lines.append(
        "SUPPORTING and HISTORICAL/CURRICULAR edges remain evidence but do not "
        "force stage precedence."
    )
    lines.append(
        "Curricular containers such as Calc III are excluded from the stages and "
        "are not used as dependency proof."
    )
    lines.append("")
    lines.append("## Staged teaching hypothesis")
    lines.append("")

    for stage in hypothesis["stages"]:
        index = stage["stage"]
        lines.append(f"### Stage {index}")
        lines.append("")
        lines.append(
            "**Within-stage status:** hypothesis space; no order is mathematically "
            "forced by the current dependency graph."
        )
        lines.append("")

        for node_id in sorted(
            stage["node_ids"],
            key=lambda item: nodes[item]["label"].lower(),
        ):
            label = nodes[node_id]["label"]
            family = nodes[node_id]["family"]
            predecessors = sorted(
                (
                    edge
                    for edge in incoming.get(node_id, [])
                    if edge["from"] in stage_by_node
                ),
                key=lambda edge: nodes[edge["from"]]["label"].lower(),
            )

            if predecessors:
                evidence = "; ".join(
                    f"{nodes[edge['from']]['label']} "
                    f"[{edge['class']}, stage {stage_by_node[edge['from']]}]"
                    for edge in predecessors
                )
                lines.append(
                    f"- **{label}** ({BT}{node_id}{BT}) — {family}. "
                    f"Earlier-stage dependency evidence: {evidence}."
                )
            else:
                lines.append(
                    f"- **{label}** ({BT}{node_id}{BT}) — {family}. "
                    "No incoming HARD/STRONG edge from another teaching node."
                )
        lines.append("")

    lines.append("## Constraint versus hypothesis")
    lines.append("")
    lines.append("| ID | Kind | Statement |")
    lines.append("|---|---|---|")
    for note in hypothesis["hypothesis_notes"]:
        lines.append(
            f"| {note['id']} | {note['kind']} | {note['statement']} |"
        )
    lines.append("")

    lines.append("## Excluded curricular containers")
    lines.append("")
    for node_id in hypothesis["excluded_curricular_containers"]:
        lines.append(f"- {nodes[node_id]['label']} ({BT}{node_id}{BT})")
    lines.append("")

    lines.append("## Unresolved dependency questions")
    lines.append("")
    inventory_questions = {
        item["id"]: item for item in inventory["open_questions"]
    }
    for question_id in hypothesis["unresolved_questions"]:
        item = inventory_questions[question_id]
        related = ", ".join(
            nodes[node_id]["label"] for node_id in item["related_nodes"]
        )
        lines.append(
            f"- **{question_id} — {item['question']}** Related nodes: "
            f"{related}. Reason: {item['reason']}"
        )
    lines.append("")

    lines.append("## Reproduction")
    lines.append("")
    lines.append("From the repository root:")
    lines.append("")
    lines.append(BT * 3 + "bash")
    lines.append("python scripts/audit_core_e3_teaching_hypothesis.py")
    lines.append("python scripts/audit_core_e3_teaching_hypothesis.py --self-test")
    lines.append("python scripts/generate_core_e3_teaching_hypothesis.py --check")
    lines.append(BT * 3)
    lines.append("")

    return "\n".join(lines)


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument(
        "--root",
        type=Path,
        default=Path(__file__).resolve().parents[1],
        help="Repository root.",
    )
    parser.add_argument(
        "--check",
        action="store_true",
        help="Fail when the committed generated report is stale.",
    )
    parser.add_argument(
        "--stdout",
        action="store_true",
        help="Print the generated report without writing it.",
    )
    args = parser.parse_args()

    root = args.root.resolve()
    expected = render(root)
    output = root / OUTPUT_PATH

    if args.stdout:
        print(expected, end="")
        return 0

    if args.check:
        if not output.is_file():
            print(f"generated report is missing: {OUTPUT_PATH.as_posix()}")
            return 1
        actual = output.read_text(encoding="utf-8")
        if actual != expected:
            print(
                "generated E3 teaching-hypothesis report is stale; run "
                "python scripts/generate_core_e3_teaching_hypothesis.py"
            )
            return 1
        print("e3_generated_report_current=1")
        return 0

    output.parent.mkdir(parents=True, exist_ok=True)
    output.write_text(expected, encoding="utf-8")
    print(f"wrote {OUTPUT_PATH.as_posix()}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
